### ISSUE TITLE
Can define drush as a custom command?

### ISSUE THREAD

**Issue by abelperezlindo** [tyler36/ddev-cypress#40] opened 2024-08-02 20:10 UTC
Is there any way this command can work with ddev and this plugin?
thanks

```javascript
Cypress.Commands.add('loginAs', (uid) => {
  cy.exec(`drush uli --uid=${uid}`, {failOnNonZeroExit: false}).then((response) => {
    cy.log("response is " + stdout);
  })
})
```

**Comment by rfay** [comment] 2024-08-02 20:51
I'm no expert, but `drush` isn't available as is inside the cypress container, so this would somehow have to be executed in the web container. It would be a useful thing. I do think there are other approaches to cypress testing that use the cypress capabilities inside the web container.

**Comment by abelperezlindo** [comment] 2024-08-02 21:01
Thanks for your comment, I'll look into another alternative.
Being able to use drush in a custom cypress command would be very useful.
Regards.

**Comment by tyler36** [comment] 2024-08-05 00:24
@abelperezlindo 

Closing. Sorry, this add-on uses a cypress container, that, by design, is unable to see the drush (web) container.

You could try setting up an API endpoint that runs the drush command and returns the needed data. Make sure you limit it to test environment though. :)

**Closed by tyler36** 2024-08-05 00:24 UTC
